### ISSUE TITLE
KeyError: 'hashtags'

### ISSUE THREAD

**Issue by pabluk** [sre-paris/reliability.re#35]
This [build](https://github.com/sre-paris/reliability.re/runs/1300788476?check_suite_focus=true) failed with this error message:
```
sre-paris/reliability.re
/home/runner/work/_temp/_github_workflow/event.json
Traceback (most recent call last):
  File "./scripts/create-content/main.py", line 82, in <module>
    main(filename)
  File "./scripts/create-content/main.py", line 61, in main
    hashtags = data["issue"]["hashtags"]
KeyError: 'hashtags'
Error: Process completed with exit code 1.
```
it's probably due to the fact github issue don't include custom fields on the payload. To be confirmed.

**Comment by sterchelen** [comment]
@pabluk I thought that the hashtags field was visible while writing an issue...
To bypass this problem we could use the labels's issue as hashtags.
This way we could avoid exotic hashtags.
What do you think?

**Comment by pabluk** [comment]
> @pabluk I thought that the hashtags field was visible while writing an issue...

I thought the same thing, I also saw that the `hashtags` https://github.com/sre-paris/reliability.re/blob/main/.github/ISSUE_TEMPLATE/new-content.md isn't showing when open a new content issue.

> To bypass this problem we could use the labels's issue as hashtags.
> This way we could avoid exotic hashtags.
> What do you think?

Yeah, that could simplify the tag management! How do you see that? Having a pre-defined list of tags? I don't know if an external contributor has the right to create labels by themself.

**Comment by sterchelen** [comment]
> Yeah, that could simplify the tag management! How do you see that? Having a pre-defined list of tags? I don't know if an external contributor has the right to create labels by themself.

Argh .... can not assign a label by an external contributor .... Then we have to modify the template to make visible the `hashtags` field 
https://github.com/sre-paris/reliability.re/blame/main/.github/ISSUE_TEMPLATE/new-content.md#L13

**Comment by pabluk** [comment]
> Argh .... can not assign a label by an external contributor

By the way, I just add you to the list of admins if you need to change or test something with the labels or settings on the orga.

> Then we have to modify the template to make visible the `hashtags` field https://github.com/sre-paris/reliability.re/blame/main/.github/ISSUE_TEMPLATE/new-content.md#L13

Maybe moving the `hashtags` field just after the `url` field:
```
---

url: https://example.com/
hashtags: <-- here
---
```
?

**Comment by sterchelen** [comment]
> I just add you to the list of admins

Thank you :smiley: 

> Maybe moving the `hashtags` field just after the `url` field:

Agree :100:

**Comment by pabluk** [comment]
https://github.com/sre-paris/reliability.re/pull/37 was merged so we can close this issue here.
