### ISSUE TITLE
SLO — From Nothing to… Production

### ISSUE THREAD

**Issue by pabluk** [sre-paris/reliability.re#44]
url: https://geototti21.medium.com/slo-from-nothing-to-production-91b8d4270bd5
hashtags: #SLOs,#SRE
---
If you don’t know how to start introducing SLOs at work, this a great example from Ioannis (@geototti21) and his journey to bring SLOs into his organization with a clear path and framework. As he said “Explain how SLOs can be an important internal tracking target that is tougher than your SLA. Also, mention how we can use the SLOs to offer better SLAs than “service uptime” if we are asked”

**Comment by geototti21** [comment]
@pabluk thanks for sharing this 🙂

**Comment by pabluk** [comment]
No problem and thanks to you @geototti21 for telling and sharing your story, it's very inspirational :+1:
