### ISSUE TITLE
Only trigger build and deploy on content files

### ISSUE THREAD

**Issue by pabluk** [sre-paris/reliability.re#5]
In order to avoid deploying all the entire Hugo site on changes that don't include changes on the HTML output, for example changes on:

* README.md
* LICENSE
* etc.

This file needs to be improved https://github.com/sre-paris/reliability.re/blob/main/.github/workflows/gh-pages.yml

**Comment by sterchelen** [comment]
@pabluk is this issue still relevant?

**Comment by pabluk** [comment]
> @pabluk is this issue still relevant?

@sterchelen yes, it's and any contribution is more than welcome :slightly_smiling_face:

I've updated the link to workflow file [gh-pages.yml](https://github.com/sre-paris/reliability.re/blob/main/.github/workflows/gh-pages.yml) because it was renamed some weeks ago.

**Comment by pabluk** [comment]
Fixed by @sterchelen via https://github.com/sre-paris/reliability.re/pull/15 using the [path-ignore](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-ignoring-paths) keyword.
