### ISSUE TITLE
A guide to the reliability talks at AWS re:Invent

### ISSUE THREAD

**Issue by GeraldC13** [sre-paris/reliability.re#52]
url: https://www.gremlin.com/blog/a-guide-to-the-reliability-talks-at-aws-re-invent/
hashtags: #AWS, #SRE
---
Top picks of **reliability-focused talks** on AWS re:Invent (virtual) from @Ana_M_Medina a Sr Chaos Eng. at @GremlinInc

**Comment by pabluk** [comment]
Nice article @GeraldC13! by the way, don't forget that we can also use mentions on Twitter, so if you can edit the issue's description to add `@Ana_M_Medina` and `@GremlinInc` could be awesome. The PR will be updated automatically. Thanks!

**Comment by GeraldC13** [comment]
Sure, you're right. Just did it. I'll keep that in mind for the next ones.
