### ISSUE TITLE
Google Kubernetes Engine on autopilot mode

### ISSUE THREAD

**Issue by tormath1** [sre-paris/reliability.re#64]
url: https://techcrunch.com/2021/02/24/google-cloud-puts-its-kubernetes-engine-on-autopilot
hashtags: 
---

Using GKE autopilot mode, you will have less to manage and more to play!

**Comment by pabluk** [comment]
I've just made an update on the description to re-launch the Github Action for the PR #65 using the latest version of master after the fix of #67.
